version: '3'
services:
  web:
    container_name: charging
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/code
      - static:/code/static-files
    command: sh ./entrypoint.sh
    networks:
      - outside

  nginx:
    build: ./nginx
    ports:
      - "9080:9080"
    restart: always
    volumes:
      - ./:/code
      - static:/code/static-files
    depends_on:
      - web
    networks:
      - outside

volumes:
  static:

networks:
  outside:
    external: true
