version: '3'
services:
  web:
    container_name: charging_stats
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9080:9080"
    volumes:
      - ./:/code
    command: sh ./entrypoint.sh
    networks:
      - outside

  nginx:
    build: ./nginx
    ports:
      - "9081:9081"
    restart: always
    volumes:
      - ./:/code
    depends_on:
      - web
    networks:
      - outside

volumes:
  static: